version: '3.8'

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fraud-detection-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./MongoDB/fraud-detectionDB:/MongoDB/fraud-detectionDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
      MONGO_INITDB_DATABASE: $DB_DATABASE