const bankVariations = {
    "IOBBK": ["indian overseas bank", "iob"],
    "SCBK": ["standard chartered bank", "sc"],
    "TMBBK": ["tamilnad mercantile bank", "tmb"],
    "DBBK": ["deutsche bank", "deutsche"],
    "DBSBK": ["dbs digibank", "dbs"],
    "APGBBK": ["andhra pragathi gramin bank", "andhra pragathi"],
    "RMGBBK": ["rajasthan marudhar gramin bank", "rajasthan marudhar gramin"],
    "CGGBBK": ["chaitanya godavari gramin bank", "chaitanya godavari gramin"],
    "BGGBBK": ["baroda gujarat gramin bank", "bharoda gujarat", "bggb"],
    "HPGBBK": ["himachal pradesh gramin bank", "himachal pradesh", "hpgb"],
    "DBGBBK": ["madhya bihar gramin bank(dakshin bihar gramin bank )", "madhya bihar", "dbgb"],
    "KNSBBK": ["shree kadi nagarik sahakari bank ltd", "kadi nagarik", "knsb"],
    "JKGBBK": ["j & k grameen bank", "j & k grameen", "jkgb"],
    "DNBBK": ["the ssk co-op bank", "ssk", "ssk cooperative"],
    "VCBLBK": ["the visakhapatnam cooperative bank ltd.", "visakhapatnam", "visakhapatnam cooperative"],
    "JCUBBK": ["the jampeta co-operative urban bank ltd", "the jampeta co-operative", "the jampeta co-operative cooperative"],
    "GCBLBK": ["the gandhidham co-operative bank limited", "the gandhidham co-operative", "the gandhidham co-operative cooperative"],
    "HSBCBK": ["hsbc"],
    "SPCBLBK": ["the surat peoples co op bank", "surat peoples"],
    "CITIBK": ["citi bank", "citi"],
    "BUCBBK": ["bhilwara urban co-operative bank ltd", "bhilwara urban", "cleartax"],
    "NCBBK": ["the national co-operative bank ltd", "the national co-operative", "the national co-operative cooperative"],
    "SMCBLBK": ["shri mahalaxmi co-op bank ltd kolhapur", "shri mahalaxmi co-op", "shri mahalaxmi co-op cooperative kolhapur"],
    "NCBBK": ["union co-operative bank ltd.", "union co-operative", "union co-operative cooperative"],
    "UPCBLBK": ["uttar pradesh co-operative bank ltd", "uttar pradesh", "uttar pradesh cooperative"],
    "BDCCBBK": ["bharuch district central co-operative bank ltd", "bharuch district central", "bharuch district central cooperative"],
    "MNSBLBK": ["shree mahuva nagrik sahkari bank ltd.", "shree mahuva nagrik", "shree mahuva nagrik cooperative"],
    "SVSBLBK": ["shree vardhaman sahakari bank ltd", "shree vardhaman sahakari", "shree vardhaman sahakari cooperative"],
    "CSBBK": ["catholic syrian bank", "csb"],
    "KVBBK": ["karur vysya bank", "kvb"],
    "KOTAKBK": ["kotak mahindra bank", "kotak"],
    "SBIBK": ["state bank of india", "sbi"],
    "AIRTELBK": ["airtel payments bank", "airtel"],
    "AUBANKBK": ["au small finance bank", "au"],
    "TBSBLBK": ["thane bharat sahakari bank", "thane bharat"],
    "CGBANKBK": ["chhatisgarh rajya gramin bank", "chhatisgarh rajya gramin"],
    "TGBHYDBK": ["telangana gramin bank", "telangana gramin"],
    "JJSBLBK": ["jalgaon janta co op bank", "jalgaon janta co op"],
    "BRKGBBK": ["baroda rajasthan kshetriya gramin bank", "baroda rajasthan", "brkgb"],
    "TSCABBK": ["telangana state co op apex bank", "telangana apex", "tsca"],
    "APCOBBK": ["andhra pradesh state cooperative bank", "andhra pradesh", "apcob"],
    "CSBANKBK": ["chartered sahakari bank niyamitha", "chartered sahakari", "chartered sahakari cooperative"],
    "HPSCBBK": ["the himachal pradesh state co-operative bank ltd", "himachal pradesh", "himachal cooperative"],
    "NESFBBK": ["north east small finance bank limited", "north east", "north east bank"],
    "KMNSBBK": ["kankaria mainagar nagrik sahakari bank ltd", "kankaria mainagar nagrik", "kankaria mainagar nagrik cooperative"],
    "SMBANKBK": ["the sangamner merchants co op bank ltd", "the sangamner merchants", "the sangamner merchants cooperative"],
    "VJSBLBK": ["vasai janata sahakari bank ltd", "vasai janata", "vasai janata cooperative"],
    "UCBLBBK": ["urban co-operative bank ltd, bareilly", "urban co-operative bank", "urban co-operative cooperative bareilly"],
    "JSCBLBK": ["janatha seva cooperative bank ltd bank", "janatha seva cooperative", "janatha seva cooperative cooperative"],
    "AUCBLBK": ["arihant urban co-operative bank ltd", "arihant urban", "arihant urban cooperative"],
    "VPMCCBBK": ["the villupuram district central co-op bank ltd", "the villupuram district central", "the villupuram district central cooperative"],
    "BNSBLBK": ["balasinor nagarik sahakari bank ltd", "balasinor nagarik sahakari", "balasinor nagarik sahakari cooperative"],
    "TGUCBBK": ["the gandhinagar urban coop bank ltd", "the gandhinagar urban coop bank", "the gandhinagar urban coop bank cooperative"],
    "DHUSBNBK": ["the davanagere harihar urban sahakara bank niyamitha", "the davanagere harihar urban sahakara bank", "the davanagere harihar urban sahakara bank cooperative niyamitha"],
    "MIECBBK": ["the makarpura industrial estate cooperative bank ltd.", "the makarpura industrial estate cooperative bank", "the makarpura industrial estate cooperative bank cooperative"],
    "AMAZONBK": ["amazon pay (india) private limited", "amazon pay (india) private", "amazon pay (india) private cooperative"],
    "YESBANKBK": ["yes bank", "yes"],
    "JKBANKBK": ["jammu & kashmir bank", "j&k bank"],
    "DNSBANKBK": ["dombivli nagri sahakari bank", "dns"],
    "SGBRRBBK": ["saurashtra gramin bank", "saurashtra gramin"],
    "JRGBANKBK": ["jharkhand rajya gramin bank", "jharkhand rajya gramin"],
    "BCCBBK": ["bassein catholic co-operative bank", "bassein catholic co-operative"],
    "TUCBLDBK": ["urban co op bankltd, dharangaon", "urban co-op", "tucb"],
    "SHGBBK": ["sarva haryana gramin bank", "sarva haryana", "shgb"],
    "PGBBK": ["punjab gramin bank", "punjab", "pgb"],
    "SCCBANKBK": ["sarvodaya commercial co-operative bank", "sarvodaya commercial", "sccb"],
    "AMCBANKBK": ["the ahmednagar merchants co-op bank ltd", "ahmednagar merchants", "amc cooperative"],
    "PUCBBK": ["pali urban co-operative bank ltd", "pali urban", "pali urban cooperative"],
    "SRCBBK": ["sri rama co-operative bank ltd", "sri rama", "sri rama cooperative"],
    "NUCBBK": ["the new urban co-operative bank ltd.rampur", "the new urban", "the new urban cooperative rampur"],
    "RCCBANKBK": ["the rajkot commercial co op bank ltd.", "the rajkot commercial", "the rajkot commercial cooperative"],
    "MNSBANKBK": ["the mandvi nagarik sahakari bank ltd", "the mandvi nagarik", "the mandvi nagarik cooperative"],
    "GNCBBK": ["the gandhinagar nagrik cooperative bank ltd", "the gandhinagar nagrik", "the gandhinagar nagrik cooperative"],
    "DMCBANKBK": ["dhanera mercantile co-operative bank ltd", "dhanera mercantile", "dhanera mercantile cooperative"],
    "GPCBANKBK": ["the gandevi peoples co operative bank limited", "the gandevi peoples", "the gandevi peoples cooperative"],
    "BNSBBK": ["baran nagrik sahakari bank ltd", "baran nagrik", "baran nagrik cooperative"],
    "RPCBANKBK": ["rajkot peoples cooperative bank ltd", "rajkot peoples", "rajkot peoples cooperative"],
    "VDCBANKBK": ["the valsad district central co-operative bank ltd", "the valsad district central", "the valsad district central cooperative"],
    "UNSBBK": ["unjha nagarik sahakari bank ltd", "unjha nagarik", "unjha nagarik cooperative"],
    "VCCBANKBK": ["the vellore district central co-op bank ltd.", "the vellore district central", "the vellore district central cooperative"],
    "CUDBANKBK": ["the cuddalore district central co-op bank limited", "the cuddalore district central", "the cuddalore district central cooperative"],
    "DGLCCBBK": ["dindigul central co-operative bank ltd", "dindigul central co-operative", "dindigul central co-operative cooperative"],
    "KCCBANKBK": ["the kumbakonam central co-op bank limited", "the kumbakonam central co-op", "the kumbakonam central co-op cooperative"],
    "TCCBANKBK": ["the thanjavur central cooperative bank ltd.", "the thanjavur central cooperative", "the thanjavur central cooperative cooperative"],
    "LUCBANKBK": ["laxmi urban co-op. bank ltd. latur.", "laxmi urban co-op.", "laxmi urban co-op. cooperative latur"],
    "MEGCABBK": ["the meghalaya cooperative apex bank ltd.", "the meghalaya cooperative apex", "the meghalaya cooperative apex cooperative"],
    "IDBIBANKBK": ["idbi bank", "idbi"],
    "PNBINDIABK": ["punjab national bank", "pnb"],
    "RBLBANKBK": ["rbl bank", "rbl"],
    "UCOBANKBK": ["uco bank", "uco"],
    "DCBBANKBK": ["dcb bank", "dcb"],
    "MUCBANKBK": ["mehasana urban co op bank", "mehasana urban"],
    "KVGBANKBK": ["karnataka vikas gramin bank", "karnataka vikas"],
    "IJSBANKBK": ["kallapanna arwade ichalkaranji janata sahakari bank", "kallapanna arwade ichalkaranji"],
    "APGVBANKBK": ["andhra pradesh gramin vikas bank", "andhra pradesh gramin vikas"],
    "CEDGEINBBK": ["meghalaya rural bank", "meghalaya rural"],
    "SVCBANKBK": ["svc bank", "svc"],
    "MSCBANKBK": ["maharashtra state cooperative bank", "maharashtra", "mscb"],
    "PBGBANKBK": ["paschim banga gramin bank", "paschim banga", "pbgb"],
    "KDCCBANKBK": ["the kaira district central co-op. bank ltd.", "kaira district", "kaira district cooperative"],
    "RDCBANKBK": ["shri rajkot district co op bank ltd", "rajkot district", "rajkot district cooperative"],
    "SVCBHNPBK": ["sri vasavamba cooperative bank ltd", "sri vasavamba", "sri vasavamba cooperative"],
    "APEXBANKBK": ["madhya pradesh rajya sahakari bank maryadit", "madhya pradesh", "madhya pradesh cooperative"],
    "ITUBANKBK": ["irinjalakuda town co-operative bank ltd", "irinjalakuda town", "irinjalakuda town cooperative"],
    "JPCBANKBK": ["the jalgaon peoples co-op bank ltd.", "the jalgaon peoples", "the jalgaon peoples cooperative"],
    "AJMSBANKBK": ["amreli jilla madhyastha sahakari bank ltd", "amreli jilla", "amreli jilla cooperative"],
    "HNSBANKBK": ["himatnagar nagarik sahakari bank ltd", "himatnagar nagarik", "himatnagar nagarik cooperative"],
    "KTCBANKBK": ["the kodungallur town co-operative bank ltd", "the kodungallur town", "the kodungallur town cooperative"],
    "RSCBBK": ["the rajasthan state co-operative bank ltd", "the rajasthan state", "the rajasthan state cooperative"],
    "PUCBANKBK": ["people's urban co-operative bank ltd", "people's urban", "people's urban cooperative"],
    "DCCBINBBK": ["jila sahakari kendriya bank maryadit khargone", "jila sahakari kendriya", "jila sahakari kendriya cooperative khargone"],
    "JSKBANKBK": ["jila sahakari kendriya bank maryadit raipur", "jila sahakari kendriya", "jila sahakari kendriya cooperative raipur"],
    "JSKBDURGBK": ["jila sahakari kendriya bank mydt. durg", "jila sahakari kendriya", "jila sahakari kendriya cooperative durg"],
    "PDPBANKBK": ["pdp bank karad bank", "pdp bank karad", "pdp bank karad cooperative"],
    "INDIALEIBK": ["warangal urban cooperative bank ltd", "warangal urban", "warangal urban cooperative"],
    "VPCBANKBK": ["the veraval peoples coop bank ltd", "the veraval peoples coop", "the veraval peoples coop cooperative"],
    "SBKBANKBK": ["swatantrya senani late shripal alase (kaka) kurundwad urban co-op bank ltd; kurundwad", "swatantrya senani late shripal alase (kaka) kurundwad", "swatantrya senani late shripal alase (kaka) kurundwad cooperative"],
    "NMCBANKBK": ["the nanded merchants coop bank ltd nanded", "the nanded merchants coop", "the nanded merchants coop cooperative nanded"],
    "TDCCBANKBK": ["the tiruchirapalli dist. cent cooperative bank ltd", "the tiruchirapalli dist. cent", "the tiruchirapalli dist. cent cooperative"],
    "VMCBANKBK": ["vidarbha merchants urban coop bank ltd., hinganghat", "vidarbha merchants urban coop", "vidarbha merchants urban coop cooperative hinganghat"],
    "LIVQUIKBK": ["livquik technology (india) private limited", "livquik technology (india) private", "livquik technology (india) private cooperative limited"],
    "AXISBANKBK": ["axis bank", "axisbank", "axis"],
    "HDFCBANKBK": ["hdfc bank", "hdfc"],
    "INDUSINDBK": ["indusind bank", "indusind"],
    "FINOBANKBK": ["fino payments bank", "fino"],
    "DHANBANKBK": ["dhanlaxmi bank", "dhanlaxmi"],
    "ESAFBANKBK": ["esaf small finance bank", "esaf"],
    "NSDLBANKBK": ["nsdl payments bank", "nsdl"],
    "UTKARSHBK": ["utkarsh small finance bank", "utkarsh"],
    "JANABANKBK": ["jana small finance bank", "jana"],
    "SUTEXBANKBK": ["the sutex co op bank", "sutex"],
    "SUCOBANKBK": ["suco souharda sahakari bank ltd", "suco"],
    "AMCOBANKBK": ["the ahmedabad mercantile coop bank", "ahmedabad mercantile", "amco"],
    "ADCBANKBK": ["the ahmedabad district coop bank", "ahmedabad district", "adc"],
    "SKBANKBK": ["the sabarkantha district central coop bank ltd", "sabarkantha district", "sabarkantha district cooperative"],
    "GDCCBANKBK": ["the gadchiroli district central co-operative bank", "gadchiroli district", "gadchiroli district cooperative"],
    "BMCBBANKBK": ["the banaskantha mercantile co-operative bank limited", "banaskantha mercantile", "banaskantha mercantile cooperative"],
    "JALNABK": ["jalna merchant's cooperative bank ltd., jalna", "jalna merchant's", "jalna merchant's cooperative"],
    "JSBLBANKBK": ["janakalyan sahakari bank", "janakalyan", "janakalyan cooperative"],
    "MPSSBANKBK": ["manvi pattana souharda sahakari bank ni", "manvi pattana", "manvi pattana cooperative"],
    "RAZORPAYBK": ["shri chhatrapathi rajarsshi shahu bank", "shahu", "shahu bank"],
    "SEWABANKBK": ["shri mahila sewa sahakari bank limited", "shri mahila sewa", "shri mahila sewa cooperative"],
    "KDCCBANKBK": ["kolhapur district central co-operative bank limited", "kolhapur district", "kolhapur district cooperative"],
    "VVCCBANKBK": ["the vallabh vidyanagar commercial co-operative bank ltd", "vallabh vidyanagar", "vallabh vidyanagar cooperative"],
    "MODELBANKBK": ["model co-operative bank limited", "model", "model cooperative"],
    "VDNSBANKBK": ["vikramaditya nagrik sahakari bank", "vikramaditya", "vikramaditya cooperative"],
    "GUBANKBK": ["the godhra urban coop bank ltd", "the godhra urban", "the godhra urban cooperative"],
    "JCOMBANKBK": ["the junagadh commercial co-op bank ltd", "the junagadh commercial", "the junagadh commercial cooperative"],
    "BCCBANKBK": ["the baroda city co operative bank ltd", "the baroda city co operative", "the baroda city co operative cooperative"],
    "DUCBBANKBK": ["dausa urban cooperative bank ltd", "dausa urban", "dausa urban cooperative"],
    "MEDAKDCCBBK": ["the district co­operative central bank ltd. medak", "the district co­operative central", "the district co­operative central cooperative medak"],
    "NAMCOBANKBK": ["the nasik merchant's co-operative bank ltd", "the nasik merchant's co-operative", "the nasik merchant's co-operative cooperative"],
    "CDCCBANKBK": ["the coimbatore district central co-op bank limited", "the coimbatore district central", "the coimbatore district central cooperative"],
    "MIZOAPEXBK": ["mizoram co-operative apex bank ltd", "mizoram co-operative apex", "mizoram co-operative apex cooperative"],
    "EDCCBANKBK": ["the erode district central co-operative bank ltd", "the erode district central co-operative", "the erode district central co-operative cooperative"],
    "DDCCBANKBK": ["dharmapuri district central co-op bank limited", "dharmapuri district central co-op", "dharmapuri district central co-op cooperative"],
    "TNYCCBANKBK": ["the tirunelveli district central co-op bank ltd", "the tirunelveli district central co-op", "the tirunelveli district central co-op cooperative"],
    "KKDCCBANKBK": ["the kanyakumari district central cooperative bank", "the kanyakumari district central", "the kanyakumari district central cooperative"],
    "GOCCBANKBK": ["sarakari naukarara sahakari bank niyamit vijayapura", "sarakari naukarara sahakari", "sarakari naukarara sahakari cooperative vijayapura"],
    "MSCOBANKBK": ["m.s. co-operative bank limited.", "m.s. co-operative", "m.s. co-operative cooperative"],
    "TRANSERVEBK": ["transerv limited", "transerv", "transerv cooperative"],
    "TRIOTECHBK": ["bajaj finance limited", "bajaj finance", "bajaj finance cooperative"],
    "PINELABSBK": ["pinelabs private limited", "pinelabs private", "pinelabs private cooperative limited"],
    "MOBIKWIKBK": ["one mobikwik systems private limited", "one mobikwik systems private", "one mobikwik systems private cooperative limited"],
    "ICICIBANKBK": ["icici bank", "icici"],
    "INDIANBANKBK": ["indian bank", "indian"],
    "PAYTMBANKBK": ["paytm payments bank", "paytm"],
    "SBMBANKBK": ["sbm bank", "sbm"],
    "RNSBINDIABK": ["rajkot nagrik sahakari bank", "rajkot nagrik"],
    "MAHAGRAMINBK": ["maharashtra gramin bank", "maharashtra gramin"],
    "GSCBANKBK": ["gujarat state co-operative bank", "gujarat state cooperative"],
    "HASTIBANKBK": ["hasti co op bank", "hasti"],
    "AGVBANKBK": ["assam gramin vikas bank", "assam gramin vikas"],
    "UJJIVANSFBBK": ["ujjivan small finance bank", "ujjivan"],
    "MALADBANKBK": ["the malad sahakari bank", "malad", "malad bank"],
    "VIKASBANKBK": ["vikas souharda co-op bank", "vikas", "vikas cooperative"],
    "NUTANBANKBK": ["nutan nagriksahakari bank", "nutan nagrik", "nutan nagrik bank"],
    "PRIYABANKBK": ["priyadarshini nagari sahakari bank ltd jalna", "priyadarshini nagari", "priyadarshini nagari cooperative"],
    "BANASBANKBK": ["the banaskantha district central co-op. bank ltd.", "banaskantha district", "banaskantha district cooperative"],
    "KOKANBANKBK": ["kokan merchantile co-operative bank ltd", "kokan merchantile", "kokan merchantile cooperative"],
    "SUMCOBANKBK": ["the surat mercantile coop bank ltd", "the surat mercantile", "the surat mercantile cooperative"],
    "CMCBANKBK": ["colour merchants co-operative bank ltd", "colour merchants", "colour merchants cooperative"],
    "PRATAPBANKBK": ["the pratap co-operative bank ltd", "the pratap", "the pratap cooperative"],
    "CNSBANKBK": ["the chembur nagarik sahakari bank", "the chembur nagarik", "the chembur nagarik cooperative"],
    "SUDHABANKBK": ["sudha co-operative urban bank ltd", "sudha co-operative", "sudha co-operative cooperative"],
    "IPCBANKBK": ["indore premier co-operative bank ltd indore", "indore premier co-operative", "indore premier co-operative cooperative"],
    "PALUSBANKBK": ["palus sahakari bank ltd", "palus", "palus cooperative"],
    "NARODABANKBK": ["the naroda nagarik co-operative bank", "the naroda nagarik co-operative", "the naroda nagarik co-operative cooperative"],
    "SCSMSBANKBK": ["shri chatrapati shivaji maharaj sahakari", "shri chatrapati shivaji maharaj", "shri chatrapati shivaji maharaj cooperative"],
    "RAIPURBK": ["the raipur urban mercantile co-op bank", "the raipur urban mercantile", "the raipur urban mercantile cooperative"],
    "KAMCOBANKBK": ["kashmir mercantile cooperative bank ltd.", "kashmir mercantile cooperative", "kashmir mercantile cooperative cooperative"],
    "AJARABANKBK": ["the ajara urban coop. bank ltd", "the ajara urban coop.", "the ajara urban coop. cooperative"],
    "VRDCCBANKBK": ["the virudhunagar district central cooperative bank ltd", "the virudhunagar district central cooperative", "the virudhunagar district central cooperative cooperative"],
    "SOUHARDABK": ["sri seetharaghava souharda sahakara bank niyamitha", "sri seetharaghava souharda sahakara", "sri seetharaghava souharda sahakara cooperative niyamitha"],
    "DHANBADCCBBK": ["the dhanbad central co-operative bank ltd.", "the dhanbad central co-operative", "the dhanbad central co-operative cooperative"],
    "ICICIBANKBK": ["icici bank", "icici", "icici bank cooperative"],
    "CANARABANKBK": ["canara bank", "canara"],
    "TJSBBANKBK": ["tjsb bank", "tjsb"],
    "IPPBONLINEBK": ["india post payments bank", "ippb"],
    "COSMOSBANKBK": ["cosmos co op bank", "cosmos"],
    "APNABANKBK": ["apna sahakari bank ltd", "apna"],
    "NKGSB-BANKBK": ["nkgsb co op bank", "nkgsb"],
    "UPICHALEGABK": ["the varanchha co op bank ltd", "varanchha"],
    "BHARATBANKBK": ["bharat co-op bank(mumbai)", "bharat", "bharat cooperative"],
    "SANDURBANKBK": ["sandur pattana souharda sahakari bank", "sandur pattana", "sandur pattana cooperative"],
    "SATARADCCBBK": ["the satara district central co-operative bank ltd.", "satara district", "satara district cooperative"],
    "AMCBLANANDBK": ["the anand mercantile co-op. bank ltd.", "anand mercantile", "anand mercantile cooperative"],
    "CCBLONLINEBK": ["citizen co-operative bank ltd - noida", "citizen cooperative", "citizen cooperative noida"],
    "NSBVIDISHABK": ["nagarik sahakari bank maryadit, vidisha", "nagarik sahakari vidisha", "nagarik sahakari vidisha bank"],
    "GAYATRIBANKBK": ["the gayatri co-operative urban bank ltd", "gayatri", "gayatri cooperative"],
    "SUDICOBANKBK": ["the surat district co-op bank ltd.", "surat district", "surat district cooperative"],
    "MONABANKBK": ["the modasa nagarik sahakari bank limited", "modasa nagarik", "modasa nagarik cooperative"],
    "SMRITIBANKBK": ["smriti nagrik sahakari bank maryadit, mandsaur", "smriti nagrik", "smriti nagrik cooperative"],
    "BASAVABANKBK": ["shri basaveshwar sahakari bank niyamit, bagalkot", "basaveshwar", "basaveshwar cooperative"],
    "ADARSHBANKBK": ["the adarsh urban co-op. bank ltd., hyderabad", "adarsh urban", "adarsh urban cooperative"],
    "SMSBANKJBK": ["shree mahavir sahakari bank ltd", "shree mahavir", "shree mahavir cooperative"],
    "CGAPEXBANKBK": ["chhattisgarh rajya sahakari bank mydt", "chhattisgarh rajya", "chhattisgarh rajya cooperative"],
    "KRANTHIBANKBK": ["the kranthi co-operative urban bank limited", "the kranthi", "the kranthi cooperative"],
    "AGRASENBANKBK": ["the agrasen co-operative urban bank ltd", "the agrasen", "the agrasen cooperative"],
    "ARVINDBANKBK": ["arvind sahakari bank ltd", "arvind", "arvind cooperative"],
    "SAMATABANKBK": ["samata sahakari bank ltd", "samata", "samata cooperative"],
    "PAVANABANKBK": ["the pavana sahakari bank ltd", "the pavana sahakari", "the pavana sahakari cooperative"],
    "THEJJSBANKBK": ["the junagadh jilla sahakari bank ltd", "the junagadh jilla", "the junagadh jilla cooperative"],
    "BMCBANKLTDBK": ["bombay mercantile co-op bank ltd", "bombay mercantile", "bombay mercantile cooperative"],
    "WARANABANKBK": ["shree warana sahakari bank ltd", "shree warana", "shree warana cooperative"],
    "SATARABANKBK": ["the satara sahakari bank ltd", "the satara sahakari", "the satara sahakari cooperative"],
    "AMBUJABANKBK": ["gujarat ambuja co-operative bank ltd", "gujarat ambuja co-operative", "gujarat ambuja co-operative cooperative"],
    "ICMBANKLTDBK": ["indore cloth market co-op bank ltd", "indore cloth market", "indore cloth market cooperative"],
    "SHAHARBANKBK": ["ahmednagar shahar sahakari bank ltd", "ahmednagar shahar", "ahmednagar shahar cooperative"],
    "TSCBANKBK": ["tripura state cooperative bank ltd", "tripura state", "tripura state cooperative"],
    "SAMATABANKBK": ["samata co-operative development bank ltd", "samata co-operative development", "samata co-operative development cooperative"],
    "AMRELIBANKBK": ["amreli nagarik sahakari bank ltd", "amreli nagarik", "amreli nagarik sahakari cooperative"],
    "RDCCBANKBK": ["the ramanathapuram district central co op bank ltd.", "the ramanathapuram district central", "the ramanathapuram district central cooperative"],
    "NILGIRISCCBBK": ["the nilgiris district central coop bank ltd", "the nilgiris district central coop", "the nilgiris district central coop cooperative"],
    "JALOREBANKBK": ["jalore nagrik sahakari bank ltd", "jalore nagrik sahakari", "jalore nagrik sahakari cooperative"],
    "KHAMMAMDCCBBK": ["district coop central bank ltd,khammam", "district coop central bank", "district coop central bank cooperative khammam"],
    "KOYANABANKBK": ["koyana sahakari bank ltd, karad", "koyana sahakari bank", "koyana sahakari bank cooperative karad"],
    "SPICEMONEYBK": ["spice money limited", "spice money", "spice money cooperative"],
    "TRIOTECHBK": ["tri o tech solutions private ltd.", "tri o tech solutions private", "tri o tech solutions private cooperative ltd."],
    "BANKOFBARODABK": ["bank of baroda", "bob"],
    "EQUITASBANKBK": ["equitas small finance bank", "equitas"],
    "BANDHANBANKBK": ["bandhan bank", "bandhan"],
    "FINCAREBANKBK": ["fincare small finance bank", "fincare"],
    "KALYANJANATABK": ["kalyan janta sahakari", "kalyan janta"],
    "KERALAGBANKBK": ["kerala gramin bank", "kerala gramin"],
    "BARODAUPBANKBK": ["baroda uttar pradesh gramin bank", "baroda uttar pradesh", "baroda up"],
    "HUTATMABANKBK": ["hutatma co op bank ltd", "hutatma", "hutatma cooperative"],
    "BARODACCBBK": ["the baroda central co-op bank ltd", "baroda central", "baroda central co-op"],
    "KALUPURBANKBK": ["kalupur commercial bank", "kalupur", "kalupur bank"],
    "ARIHANTBANKBK": ["shri arihant co-operative bank ltd", "arihant", "arihant cooperative"],
    "UUCBUDAIPURBK": ["the udaipur urban co-operative bank ltd.", "udaipur urban", "udaipur urban cooperative"],
    "KBSBANKINDIABK": ["krishna bhima samruddhi local area bank", "krishna bhima", "krishna bhima cooperative"],
    "DHARATIBANKBK": ["shree dharati co-operative bank ltd", "shree dharati", "shree dharati cooperative"],
    "SAMARTHBANKBK": ["samarth sahakari bank limited", "samarth", "samarth cooperative"],
    "MALVIYABANKBK": ["malviya urban co-operative bank limited", "malviya urban", "malviya urban cooperative"],
    "SAIBABABANKBK": ["saibaba nagari sahakari bank maryadit", "saibaba", "saibaba cooperative"],
    "SADHANABANKBK": ["sadhana sahakari bank ltd pune", "sadhana", "sadhana cooperative pune"],
    "LONAVLABANKBK": ["lonavala sahakari bank ltd", "lonavala", "lonavala cooperative"],
    "VAISHYABANKBK": ["vaishya nagari sahakari bank ltd parbhani", "vaishya nagari", "vaishya nagari cooperative parbhani"],
    "DEOGIRIBANKBK": ["deogiri nagari sahakari bank ltd aurangabad", "deogiri nagari", "deogiri nagari cooperative aurangabad"],
    "KHAMGAONBANKBK": ["the khamgaon urban co-operative bank ltd,khamgaon", "the khamgaon urban", "the khamgaon urban cooperative khamgaon"],
    "COBMAHESANABK": ["the co-operative bank of mehsana ltd", "the co-operative bank of mehsana", "the co-operative bank of mehsana cooperative"],
    "VAISHYABANKBK": ["vaishya sahakari bank ltd mumbai", "vaishya sahakari", "vaishya sahakari cooperative mumbai"],
    "NANDURABANKBK": ["the nandura urban coop bank ltd nandura", "the nandura urban", "the nandura urban cooperative nandura"],
    "GREATERBANKBK": ["the greater bombay co-operative bank limited", "the greater bombay", "the greater bombay cooperative"],
    "AJANTHABANKBK": ["ajanta urban co-op bank ltd", "ajanta urban", "ajanta urban cooperative"],
    "KALUPURBANKBK": ["the commercial cooperative bank limited", "the commercial cooperative", "the commercial cooperative cooperative"],
    "BHAVNAGARDCBBK": ["bhavnagar district co op bank ltd", "bhavnagar district", "bhavnagar district cooperative"],
    "MANSINGBANKBK": ["mansing co-operative bank ltd.", "mansing", "mansing cooperative"],
    "JAIHINDBANKBK": ["ambarnath jai hind cooperative bank ltd.", "ambarnath jai hind", "ambarnath jai hind cooperative"],
    "ABHINAVBANKBK": ["the abhinav sahakari bank ltd., mumbai", "the abhinav sahakari", "the abhinav sahakari cooperative mumbai"],
    "SADHANABANKBK": ["sadhana sahakari bank ltd. nagpur", "sadhana sahakari", "sadhana sahakari cooperative nagpur"],
    "BHAVANABANKBK": ["the bhavana rishi co-op.urban bank", "the bhavana rishi co-op.urban", "the bhavana rishi co-op.urban cooperative"],
    "PRERANABANKBK": ["prerana co-operative bank ltd", "prerana co-operative", "prerana co-operative cooperative"],
    "KHATTRIBANKBK": ["khattri co-op bank", "khattri co-op", "khattri co-op cooperative"],
    "SAMPADABANKBK": ["sampada sahakari bank ltd.,pune", "sampada sahakari", "sampada sahakari cooperative pune"],
    "KALUPURBANKBK": ["the commercial co-operative bank ltd .", "the commercial co-operative", "the commercial co-operative cooperative"],
    "MADURAIDCCBBK": ["madurai district central cooperative bank", "madurai district central cooperative", "madurai district central cooperative cooperative"],
    "NANDANIBANKBK": ["nandani sahakari bank ltd. nandani", "nandani sahakari", "nandani sahakari cooperative nandani"],
    "UMACOOPBANKBK": ["uma co-operative bank ltd", "uma co-operative", "uma co-operative cooperative"],
    "WARANGALDCCBBK": ["warangal district coop central bank ltd", "warangal district coop central bank", "warangal district coop central bank cooperative"],
    "ADILABADDCCBBK": ["adilabad district coop central bank ltd", "adilabad district coop central bank", "adilabad district coop central bank cooperative"],
    "APMAHESHBANKBK": ["a p mahesh co-operative urban bank ltd", "ap mahesh"],
    "SARASWATBANKBK": ["saraswat bank", "saraswat"],
    "GPPARSIKBANKBK": ["gp parsik", "gp parsik"],
    "SAMRIDHIBANKBK": ["the udaipur mahila urban co-operative bank ltd.", "udaipur mahila", "play"],
    "SAMRIDHIBANKBK": ["the udaipur mahila samridhi urban co-operative bank ltd.", "udaipur mahila samridhi", "samridhi"],
    "SURYODAYBANKBK": ["suryoday small finance bank ltd", "suryoday", "suryoday bank"],
    "BARAMATIBANKBK": ["the baramati sahakari bank ltd", "baramati", "baramati sahakari"],
    "RCMAHILABANKBK": ["rani channamma mahila sahakari bank belagavi", "rani channamma mahila", "rani channamma mahila cooperative"],
    "YLNSCOOPBANKBK": ["yadagiri lakshmi narasimha swamy co-op urban bank ltd", "yadagiri lakshmi narasimha swamy", "yadagiri lakshmi narasimha swamy cooperative"],
    "ASSOCIATEBANKBK": ["associate co-operative bank limited,surat", "associate", "associate cooperative surat"],
    "SHIVALIKBANKBK": ["shivalik small finance bank", "shivalik", "shivalik bank"],
    "AKOLADCCBANKBK": ["the akola district central cooperative bank ltd", "the akola district", "the akola district cooperative"],
    "JANATABANKBK": ["shri janata sahakari bank limited, halol", "shri janata", "shri janata cooperative halol"],
    "SARVODAYBANKBK": ["the sarvodaya nagrik sahakari bank limited", "the sarvodaya nagrik", "the sarvodaya nagrik cooperative"],
    "KOPURBANBANKBK": ["the kolhapur urban cooperative bank ltd., kolhapur", "the kolhapur urban", "the kolhapur urban cooperative kolhapur"],
    "TIRUPATIBANKBK": ["tirupati urban co-operative bank limited", "tirupati urban", "tirupati urban cooperative"],
    "SARASPURBANKBK": ["saraspur nagrik co-operative bank ltd", "saraspur nagrik", "saraspur nagrik cooperative"],
    "JIJAMATABANKBK": ["jijamata mahila sahakari bank ltd", "jijamata mahila", "jijamata mahila cooperative"],
    "SRISUDHABANKBK": ["sri sudha cooperative bank ltd", "sri sudha", "sri sudha cooperative"],
    "MAHAVEERBANKBK": ["the mahaveer co-operative bank ltd", "the mahaveer", "the mahaveer cooperative"],
    "MAHAVEERBANKBK": ["mahaveer co-operative urban bank limited", "mahaveer co-operative urban", "mahaveer co-operative urban cooperative"],
    "GODAVARIBANKBK": ["godavari urban co-op bank", "godavari urban", "godavari urban cooperative"],
    "KERALACOBANKBK": ["kerala state co-operative bank ltd", "kerala state co-operative", "kerala state co-operative cooperative"],
    "THEUNITYBANKBK": ["unity small finance bank limited", "unity small finance", "unity small finance cooperative"],
    "URBANBANKSDNBK": ["urban co operativa bank ltd siddharthnagar", "urban co operativa", "urban co operativa cooperative siddharthnagar"],
    "HARCOBANKBK": ["the haryana state co-operative apex bank ltd", "the haryana state co-operative apex", "the haryana state co-operative apex cooperative"],
    "ARYAVART-RRBBK": ["aryavart bank", "aryavart", "aryavart cooperative bank"],
    "TRANSCORPINTBK": ["transcorp international limited", "transcorp international", "transcorp international cooperative limited"],
    "FEDERALBANKBK": ["federal bank", "federal"],
    "IDFCFIRSTBANKBK": ["idfc bank", "idfc"],
    "KARNATAKABANKBK": ["karnataka bank", "karnataka"],
    "BANKOFINDIABK": ["bank of india", "boi"],
    "CITYUNIONBANKBK": ["city union bank", "city union"],
    "MAHANAGARBANKBK": ["gs mahanagar co op bank", "gs mahanagar"],
    "SINDHUDURGDCCBK": ["sindhudurg co-op bank", "sindhudurg", "sindhudurg bank"],
    "CAPITALBANKBK": ["capital small finance bank", "capital", "capital bank"],
    "FINGROWTHBANKBK": ["fingrowth co-operative bank ltd", "fingrowth", "fingrowth cooperative"],
    "BANKOFAMERICABK": ["bank of america na", "bank of america", "bofa"],
    "MANNDESHIBANKBK": ["mann deshi mahila sahkari bank limited", "mann deshi", "mann deshi cooperative"],
    "EENADUBANKLTDBK": ["the eenadu coop urban bank ltd", "the eenadu coop", "the eenadu coop cooperative"],
    "KOPMAHILABANKBK": ["kolhapur mahila sahakari bank ltd.", "kolhapur mahila", "kolhapur mahila cooperative"],
    "BHADRADRIBANKBK": ["bhadradri co-operative urban bank", "bhadradri", "bhadradri cooperative"],
    "MAHESHBANKPUNEBK": ["mahesh sahakari bank limited", "mahesh", "mahesh cooperative"],
    "KARNATAKAAPEXBK": ["the karnataka state co-operative apex bank limited", "the karnataka state", "the karnataka state cooperative apex"],
    "NAVNIRMANBANKBK": ["the navnirman co-operative bank", "the navnirman", "the navnirman cooperative"],
    "KARNAVATIBANKBK": ["the karnavati co.op. bank ltd", "the karnavati co.op.", "the karnavati co.op. cooperative"],
    "VALMIKIBANKBK": ["valmiki urban co-op bank ltd - pathri", "valmiki urban", "valmiki urban cooperative pathri"],
    "INDRAYANIBANKBK": ["indrayani co-operative bank ltd", "indrayani", "indrayani cooperative"],
    "VARDHAMANBANKBK": ["vardhaman [mahila] co-op. urban bank ltd", "vardhaman [mahila] co-op.", "vardhaman [mahila] co-op. cooperative"],
    "NAVSARJANBANKBK": ["navsarjan industrial co-op bank ltd", "navsarjan industrial", "navsarjan industrial cooperative"],
    "APRURALBANKBK": ["arunachal pradesh rural bank", "arunachal pradesh", "arunachal pradesh rural"],
    "KUKARWADABANKBK": ["the kukarwada nagrik sahakari bank ltd", "the kukarwada nagrik sahakari", "the kukarwada nagrik sahakari cooperative"],
    "SARVODAYABANKBK": ["the sarvodaya sahakari bank ltd", "the sarvodaya sahakari", "the sarvodaya sahakari cooperative"],
    "HASSANDCCBANKBK": ["the hassan dcc bank pvt ltd", "the hassan dcc", "the hassan dcc cooperative"],
    "ADCCBANKNAGARBK": ["the ahmednagar district central coop bank ltd", "the ahmednagar district central coop", "the ahmednagar district central coop cooperative"],
    "VCCBANKRAJKOTBK": ["vijay commercial co operative bank ltd", "vijay commercial co operative", "vijay commercial co operative cooperative"],
    "SIVAGANGAIDCCBBK": ["the sivagangai district central coop bank ltd.", "the sivagangai district central", "the sivagangai district central cooperative"],
    "SREENIDHIBANKBK": ["sreenidhi souharda sahakari bank niyamitha", "sreenidhi souharda sahakari", "sreenidhi souharda sahakari cooperative niyamitha"],
    "CCBANKCHENNAIBK": ["chennai central co-operative bank ltd.", "chennai central co-operative", "chennai central co-operative cooperative"],
    "KOTTAYAMURBANBK": ["kottayam co-operative urban bank ltd", "kottayam co-operative urban", "kottayam co-operative urban cooperative"],
    "LOKMANGALBANKBK": ["lokmanagal co op bank ltd solapur", "lokmanagal co op bank", "lokmanagal co op bank cooperative solapur"],
    "KODAGUDCCBANKBK": ["the kodagu district cooperrative central bank ltd", "the kodagu district cooperrative central bank", "the kodagu district cooperrative central bank cooperative"],
    "IDFCFIRSTBANKBK": ["idfc first bank limited", "idfc first bank", "idfc first bank cooperative"],
    "JANATABANKPUNEBK": ["janta sahakari bank pune", "janta sahakari pune"],
    "SUVARNAYUGBANKBK": ["suvarnayug sahakari bank ltd.", "suvarnayug"],
    "PRATHAMAUPBANKBK": ["prathama up gramin bank", "prathama up", "prathama"],
    "NAINITALBANKBK": ["nainital bank ltd", "nainital", "nainital bank"],
    "DARUSSALAMBANKBK": ["the darussalam cooperative urban bank ltd", "darussalam", "darussalam cooperative"],
    "INDOREPARASPARBK": ["indore paraspar sahakari bank ltd", "indore paraspar", "indore paraspar cooperative"],
    "PRIMEBANKINDIABK": ["prime co-operative bank ltd.", "prime", "prime cooperative"],
    "PANCHGANGABANKBK": ["shree panchganga nagari sahakari bank ltd", "shree panchganga", "shree panchganga cooperative"],
    "NAVIMUMBAIBANKBK": ["navi mumbai co-operative bank limited", "navi mumbai", "navi mumbai cooperative"],
    "BHAGYODAYABANKBK": ["the bhagyodaya co-operative bank limited", "the bhagyodaya", "the bhagyodaya cooperative"],
    "SAURASHTRABANKBK": ["the saurashtra co-operative bank ltd., ahmedabad", "the saurashtra", "the saurashtra cooperative ahmedabad"],
    "SREECHARANBANKBK": ["sree charan souhardha co-operative bank limited", "sree charan", "sree charan cooperative"],
    "NSBGWALIORBK": ["nagrik sahakari bank maryadit gwalior", "nagrik sahakari", "nagrik sahakari cooperative gwalior"],
    "POORNAWADIBANKBK": ["poornawadi nagrik sahakari bank m.beed.", "poornawadi nagrik", "poornawadi nagrik cooperative m.beed"],
    "BHUJCOMMBANKBK": ["the bhuj commercial co-operative bank ltd", "the bhuj commercial", "the bhuj commercial cooperative"],
    "BALLARIDCCBANKBK": ["the bellary district coop central bank ltd", "the bellary district coop central", "the bellary district coop central cooperative"],
    "KARIMNAGARDCCBBK": ["karimnagar dcc bank", "karimnagar dcc", "karimnagar dcc cooperative"],
    "RAJADHANI-BANKBK": ["rajadhani co-operative urban bank", "rajadhani co-operative", "rajadhani co-operative urban cooperative"],
    "GUARDIANBANKBK": ["guardian souharda sahakari bank niyamita", "guardian souharda sahakari", "guardian souharda sahakari cooperative"],
    "DHULEVIKASBANKBK": ["dhule vikas sahakari bank ltd", "dhule vikas", "dhule vikas sahakari cooperative"],
    "UPCBANKLIMITEDBK": ["the uttarsanda peoples coop bank ltd uttarsanda", "the uttarsanda peoples coop", "the uttarsanda peoples coop cooperative"],
    "AKOLAURBANBANKBK": ["the akola urban co-op bank limited, akola", "the akola urban co-op", "the akola urban co-op cooperative akola"],
    "NALGONDADCCBTSBK": ["nalgonda district coop central bank ltd", "nalgonda district coop central bank", "nalgonda district coop central bank cooperative"],
    "PUCBBK": ["the panipat urban cooperative bank ltd", "the panipat urban cooperative bank", "the panipat urban cooperative bank cooperative"],
    "PUSADURBANBANKBK": ["pusad urban cooperative bank ltd.", "pusad urban cooperative bank", "pusad urban cooperative bank cooperative"],
    "SOUTHINDIANBANKBK": ["south indian bank", "south indian"],
    "JIOPAYMENTSBANKBK": ["jio payments bank", "jio"],
    "MIZORAMRURALBANKBK": ["mizoram gramin bank", "mizoram gramin"],
    "VISHWESHWARBANKBK": ["the vishweshwar sahakari bank limited", "the vishweshwar sahakari"],
    "ABHYUDAYABANKBK": ["abhyudaya co-op bank ltd", "abhyudaya", "abhyudaya cooperative"],
    "VEERSHAIVBANKBK": ["shri veershaiv co-op bank ltd.", "veershaiv", "veershaiv cooperative"],
    "COASTALAREABANKBK": ["coastal local area bank ltd", "coastal local", "coastal local cooperative"],
    "POCHAMPALLYBANKBK": ["the pochampally co-operative urban bank ltd", "pochampally", "pochampally cooperative"],
    "THEKAKATIYABANKBK": ["the kakatiya co-operative urban bank limited", "the kakatiya", "the kakatiya cooperative"],
    "AKHANDANANDBANKBK": ["akhand anand co.op bank ltd", "akhand anand", "akhand anand cooperative"],
    "DEENDAYALBANKBK": ["deendayal nagari sahakari bank ltd", "deendayal nagari", "deendayal nagari cooperative"],
    "DAPOLIURBANBANKBK": ["dapoli urban co op bank ltd dapoli", "dapoli urban co op", "dapoli urban co op cooperative dapoli"],
    "PUNEPEOPLESBANKBK": ["pune peoples co-op.bank ltd.td>", "pune peoples", "pune peoples cooperative"],
    "BALOTRAURBANBANKBK": ["balotra urban co-operative bank ltd", "balotra urban", "balotra urban cooperative"],
    "RAJARAMBAPUBANKBK": ["rajarambapu sahakari bank ltd", "rajarambapu", "rajarambapu cooperative"],
    "AKOLAJANATABANKBK": ["akola janata commercial co-operative bank", "akola janata commercial", "akola janata commercial cooperative"],
    "GUNTURURBANBANKBK": ["guntur urban bank", "guntur urban", "guntur urban cooperative"],
    "JANATABANKAJARABK": ["janata sahakari bank ltd., ajara", "janata sahakari", "janata sahakari cooperative ajara"],
    "SHREEMAHESHBANKBK": ["shree mahesh co-operative bank ltd nashik", "shree mahesh co-operative", "shree mahesh co-operative cooperative nashik"],
    "MAHATMAFULEBANKBK": ["mahatma fule urban co-operative bank ltd.", "mahatma fule urban", "mahatma fule urban cooperative"],
    "NAWANAGARBANKBK": ["the nawanagar co operative bank ltd", "the nawanagar co operative", "the nawanagar co operative cooperative"],
    "SHRIADINATHBANKBK": ["shri adinath co-op bank ltd., ichalkaranji", "shri adinath co-op", "shri adinath co-op cooperative ichalkaranji"],
    "SHRIKRISHNABANKBK": ["shrikrishna co-operative bank ltd., umred", "shrikrishna co-operative bank", "shrikrishna co-operative bank cooperative umred"],
    "KAKINADATOWNBANKBK": ["the kakinada co-op town bank ltd", "the kakinada co-op town", "the kakinada co-op town cooperative"],
    "BANKOFMAHARASHTRABK": ["bank of maharashtra", "bom"],
    "MANIPURRURALBANKBK": ["manipur gramin bank", "manipur gramin"],
    "SAMRUDDHISOCIETYBK": ["samruddhi co-operative bank ltd", "samruddhi"],
    "PATANNAGARIKBANKBK": ["patan nagrik sahakari bank", "patan nagrik", "patan nagrik bank"],
    "JANASEVABANKPUNEBK": ["janaseva sahakari bank ltd pune", "janaseva", "janaseva cooperative pune"],
    "MERCHANTSBANKCTABK": ["the merchants souharda sahakari bank ltd", "merchants souharda", "merchants souharda cooperative"],
    "RAJGURUNAGARBANKBK": ["rajgurunagar sahakari bank ltd.", "rajgurunagar", "rajgurunagar cooperative"],
    "SHRIBHARATBANKBK": ["shri bharat urban co-operative bank ltd jaysingpur", "shri bharat urban", "shri bharat urban cooperative jaysingpur"],
    "ASHTAPEOPLESBANKBK": ["the ashta peoples co-op bank ltd ashta", "the ashta peoples co-op", "the ashta peoples co-op cooperative ashta"],
    "MUZAFFARNAGARDCBBK": ["muzaffarnagar district cooperative bank ltd", "muzaffarnagar district cooperative bank", "muzaffarnagar district cooperative bank cooperative"],
    "TRIPURAGRAMINBANKBK": ["tripura gramin bank", "tripura gramin"],
    "SURATNATIONALBANKBK": ["surat national co-operative bank limited", "surat national", "surat national cooperative"],
    "THANEDISTRICTBANKBK": ["the thane dist. central co-op. bank ltd", "the thane dist. central", "the thane dist. central cooperative"],
    "UDUPICOOPTOWNBANKBK": ["the udupi co-operative town bank ltd - udupi", "the udupi co-operative town", "the udupi co-operative town cooperative udupi"],
    "BICHOLIMURBANBANKBK": ["bicholim urban cooperative bank", "bicholim urban", "bicholim urban cooperative"],
    "RAJARAJESWARIBANKBK": ["the a.p. raja rajeswari mahila co operative urban bank ltd", "the a.p. raja rajeswari", "the a.p. raja rajeswari cooperative"],
    "SANTSOPANKAKABANKBK": ["sant sopankaka sahakari bank ltd.", "sant sopankaka", "sant sopankaka cooperative"],
    "MEHSANANAGRIKBANKBK": ["the mehsana nagarik sahakari bank ltd", "the mehsana nagarik sahakari", "the mehsana nagarik sahakari cooperative"],
    "SHRAMIKNAGRIKBANKBK": ["shramik nagrik sahakari bank ltd", "shramik nagrik sahakari", "shramik nagrik sahakari cooperative"],
    "BARDOLINAGRIKBANKBK": ["the bardoli nagrik sahakari bank ltd", "the bardoli nagrik sahakari", "the bardoli nagrik sahakari cooperative"],
    "UNIONBANKOFINDIABK": ["union bank of india", "ubi"],
    "PUNECANTONMENTBANKBK": ["pune cantonment sahakari bank ltd", "pune cantonment", "pune cantonment cooperative"],
    "JAMKHANDIURBANBANKBK": ["the jamkhandi urban co-operative bank ltd", "the jamkhandi urban", "the jamkhandi urban cooperative"],
    "SUNDARLALSAWJIBANKBK": ["sundarlal sawaji urban co-op bank ltd", "sundarlal sawaji", "sundarlal sawaji cooperative"],
    "BUSINESSBANKNASHIKBK": ["the business co-operative bank ltd", "the business co-operative", "the business co-operative cooperative"],
    "SHREEMAHALAXMIBANKBK": ["shree mahalaxmi urban co-op credit bank ltd.", "shree mahalaxmi urban", "shree mahalaxmi urban cooperative"],
    "CO-OPERATIVEBANKBK": ["the financial co-operative bank ltd", "the financial co-operative", "the financial co-operative cooperative"],
    "KOTTAKKALURBANBANKBK": ["kottakkal co- op urban bank ltd", "kottakkal co- op urban", "kottakkal co- op urban cooperative"],
    "PCCBANKBK": ["the pudukkottai district central co-op bank ltd.", "the pudukkottai district central", "the pudukkottai district central cooperative"],
    "SHAHADAPEOPLESBANKBK": ["the shahada peoples coop bank ltd", "the shahada peoples coop", "the shahada peoples coop cooperative"],
    "PUNJABANDSINDBANKBK": ["punjab & sind bank", "psb"],
    "KARNATAKAGRAMINBANKBK": ["pragathi krishna gramin bank", "pragathi krishna"],
    "MUNICIPALBANKMUMBAIBK": ["the municipal co-op bank", "municipal", "municipal bank"],
    "BHAGININIVEDITABANKBK": ["bhagini nivedita sahakari bank ltd,pune", "bhagini nivedita", "bhagini nivedita cooperative"],
    "KMSBANKBK": ["karnataka mahila sahakara bank niyamitha", "karnataka mahila", "karnataka mahila cooperative"],
    "SHARADBANKBK": ["sharad sahakari bank ltd manchar", "sharad sahakari", "sharad sahakari cooperative manchar"],
    "KCCBBK": ["the kancheepuram central co-operative bank limited", "the kancheepuram central co-operative", "the kancheepuram central co-operative cooperative"],
    "CENTRALBANKOFINDIABK": ["central bank of india", "cbi"],
    "VIJAYCOOPERATIVEBANKBK": ["the vijay co-operative bank ltd, ahmedabad", "vijay", "vijay cooperative"],
    "AMBAJOGAIPEOPLESBANKBK": ["ambajogai peoples co-operative bank limited", "ambajogai peoples", "ambajogai peoples cooperative"],
    "KTCBANKBK": ["the kodinar taluka cooperative banking union ltd", "the kodinar taluka", "the kodinar taluka cooperative"],
    "UTTARAKHANDGRAMINBANKBK": ["uttarakhand gramin bank", "uttarakhand gramin"],
    "MUSLIMCOOPERATIVEBANKBK": ["the muslim cooperative bank ltd", "muslim", "muslim cooperative"],
    "KANAKAMAHALAKSHMIBANKBK": ["the kanakmahalakshmi co-operative bank ltd", "kanakmahalakshmi", "kanakmahalakshmi cooperative"],
    "RAJARSHISHAHUBANKPUNEBK": ["rajarshi shahu sahakari bank limited", "rajarshi shahu", "rajarshi shahu cooperative"],
    "JNSBJODHPURNAGRIKBANKBK": ["jodhpur nagrik sahakari bank limited", "jodhpur nagrik sahakari", "jodhpur nagrik sahakari cooperative"],
    "TUTYCCBANKBK": ["the thoothukudi district central co-op bank limited", "the thoothukudi district central co-op", "the thoothukudi district central co-op cooperative"],
    "MARATHACOOPERATIVEBANKBK": ["maratha cooprative bank ltd", "maratha", "maratha cooperative"],
    "ADARSHCO-OPERATIVEBANKBK": ["adarsh cooperative bank ltd", "adarsh", "adarsh cooperative"],
    "PANCHMAHALDISTRICTBANKBK": ["the panchmahal district co operative bank ltd", "the panchmahal district", "the panchmahal district cooperative"],
    "TVMALAIDCCBBK": ["the tiruvannamalai district central coop bank limited", "the tiruvannamalai district central coop", "the tiruvannamalai district central coop cooperative"],
    "PUNEURBANBANKBK": ["pune urban co-operative bank ltd", "pune urban", "pune urban cooperative"],
    "RVGBANKBK": ["raje vikramsinh ghatge co-op. bank ltd. kagal", "raje vikramsinh ghatge co-op.", "raje vikramsinh ghatge co-op. cooperative kagal"],
    "CITIZENSCOOPERATIVEBANKJAMMUBK": ["citizens co-operative bank ltd", "citizens co-operative", "citizens co-operative cooperative"],
    "TNSCBANKBK": ["tamil nadu state apex co-op bank ltd", "tamil nadu state apex", "tamil nadu state apex cooperative"],
    "JIVAN-COMMERCIAL-CO-OPERATIVE-BANK-LTDBK": ["jivan commercial co-operative bank ltd", "jivan commercial", "jivan commercial cooperative"],
};


async function bankNameExtractor(inputText) {
    const matchedWords = [];
    const frequencyMap = {};
    const variations = bankVariations;
    const words = inputText.toLowerCase().split(' ');
    const defaultValue = ["NULLBANKNAME"];

    const regexPattern = Object.entries(variations)
        .map(([bankKey, variationsArray]) => {
            const escapedVariations = variationsArray
                .map(variation => variation.toLowerCase())
                .map(word => word.replace(/[-/\\^$*+?.()|[\]{}]/g, '\\$&'))
                .join('|');
            return `(${escapedVariations})`;
        })
        .join('|');

    const regex = new RegExp(`\\b(${regexPattern})\\b`, 'g');

    const matches = inputText.toLowerCase().match(regex);
    if (matches) {
        matches.forEach(match => {
            matchedWords.push(match);
            frequencyMap[match] = (frequencyMap[match] || 0) + 1;
        });
    }

    const matchedBanks = Object.keys(variations).filter(bankKey =>
        matchedWords.some(word => variations[bankKey].includes(word.toLowerCase()))
    );

    if (matchedBanks.length === 0) {
        const matchedWords = defaultValue
        const matchedBanks = defaultValue
        return { matchedBanks, matchedWords } // Return the default value if no matches are found
    }

    return { matchedWords, frequencyMap, matchedBanks };
}

// Example usage with a default value:
// async function main() {
//     const inputText = " as as  asasdasdasdas";
//     const result = await bankNameExtractor(inputText);
//     console.log('a0000000000000', result.matchedWords);
// }
// main()
// const text = "Dear Customer, IDFC bank Account has been locked due to incomplete KYC. Kindly download our mobile app from the following URL to update your details:";
// const { matchedWords, frequencyMap, matchedBanks } = findPartialMatches(text, bankVariations);

// console.log(bankNameExtractor(text));

// findPartialMatches(text);

module.exports = bankNameExtractor;